// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package model




// LssueOrder is the golang structure for table lssue_order.
type LssueOrder struct {
    Id           int    `orm:"id,primary"     json:"id"`           //             
    GoodsOrderSn string `orm:"goods_order_sn" json:"goodsOrderSn"` // 商品订单号  
}


// OrderChild is the golang structure for table order_child.
type OrderChild struct {
    Id              uint   `orm:"id,primary"        json:"id"`              // 编号                                                     
    Sn              string `orm:"sn"                json:"sn"`              // 本站父订单号                                             
    OrderSn         string `orm:"order_sn"          json:"orderSn"`         // 本站订单号                                               
    Money           uint   `orm:"money"             json:"money"`           // 商家本单支付金额                                         
    PayStatus       uint   `orm:"pay_status"        json:"payStatus"`       // 付款状态【1:已付款,2:申请退款 3:退款中 4:已退款】        
    CreatedTime     uint   `orm:"created_time"      json:"createdTime"`     // 下单时间                                                 
    PayTime         uint   `orm:"pay_time"          json:"payTime"`         // 付款时间                                                 
    Delivertime     uint   `orm:"delivertime"       json:"delivertime"`     // 发货时间                                                 
    Freight         uint   `orm:"freight"           json:"freight"`         // 物流费                                                   
    ConfirmTime     uint   `orm:"confirm_time"      json:"confirmTime"`     // 确认收货时间                                             
    RealSource      uint   `orm:"real_source"       json:"realSource"`      // 真实商品来源                                             
    Source          uint   `orm:"source"            json:"source"`          // 商品来源【1.云仓2.京东6.阿里7.天猫8.苏宁】               
    ThirdSn         string `orm:"third_sn"          json:"thirdSn"`         // 合作方订单号                                             
    LogisticsStatus uint   `orm:"logistics_status"  json:"logisticsStatus"` // 物流状态【1:未发货 2:已发货 3:已收货】                   
    Status          uint   `orm:"status"            json:"status"`          // 订单状态【1:下单失败 2:下单成功 3:订单完成 4:订单关闭】  
    IsDone          uint   `orm:"is_done"           json:"isDone"`          // 是否完成【1:是 2:否】                                    
    IsClose         uint   `orm:"is_close"          json:"isClose"`         // 是否关闭【1:是 2:否】                                    
    ThirdOrderState uint   `orm:"third_order_state" json:"thirdOrderState"` // 合作方订单状态：0：为取消订单，1:为有效 ,2:为下单失败    
    ThirdOrderPay   uint   `orm:"third_order_pay"   json:"thirdOrderPay"`   // 合作方订单支付状态，1成功，2失败                         
    GoodsStatus     uint   `orm:"goods_status"      json:"goodsStatus"`     // 0未发货 1已发货 2已收货 3 已完成                         
    SuccessMoney    uint   `orm:"success_money"     json:"successMoney"`    // 平台本单支付金额                                         
    ShopId          uint   `orm:"shop_id"           json:"shopId"`          // 商家id                                                   
    ThirdSn2        string `orm:"third_sn2"         json:"thirdSn2"`        // 合作方订单号(扩充)                                       
    IsRefund        uint   `orm:"is_refund"         json:"isRefund"`        // 是否退单【1:是 0:否】                                    
    IsApply         uint   `orm:"is_apply"          json:"isApply"`         // 申请售后【1:是 2:否】                                    
}


// OrderGoods is the golang structure for table order_goods.
type OrderGoods struct {
    Id              uint   `orm:"id,primary"        json:"id"`              // ID                                          
    OrderId         uint   `orm:"order_id"          json:"orderId"`         // 订单ID                                      
    GoodsOrderSn    string `orm:"goods_order_sn"    json:"goodsOrderSn"`    // 子订单sn                                    
    GoodsId         uint   `orm:"goods_id"          json:"goodsId"`         // 商品id                                      
    GoodsImage      string `orm:"goods_image"       json:"goodsImage"`      // 商品图片                                    
    OptionId        uint   `orm:"option_id"         json:"optionId"`        // 规格id                                      
    Title           string `orm:"title"             json:"title"`           // 商品名称                                    
    Total           uint   `orm:"total"             json:"total"`           // 商品总数                                    
    Price           uint   `orm:"price"             json:"price"`           // 商品价格分                                  
    RefundTime      uint   `orm:"refund_time"       json:"refundTime"`      // 退款时间                                    
    CreatedTime     uint   `orm:"created_time"      json:"createdTime"`     // 创建时间                                    
    GoodsThirdSn    string `orm:"goods_third_sn"    json:"goodsThirdSn"`    // 三方子订单号                                
    RealSource      uint   `orm:"real_source"       json:"realSource"`      // 真实来源                                    
    Source          uint   `orm:"source"            json:"source"`          // 商品来源【1:云仓2:京东6:阿里7:天猫8:苏宁】  
    PayStatus       uint   `orm:"pay_status"        json:"payStatus"`       // 付款状态【0:未付款,1:已付款】               
    DeliverName     string `orm:"deliver_name"      json:"deliverName"`     // 物流公司                                    
    DeliverNo       string `orm:"deliver_no"        json:"deliverNo"`       // 物流单号                                    
    DeliverTime     uint   `orm:"deliver_time"      json:"deliverTime"`     // 发货时间                                    
    PayPrice        uint   `orm:"pay_price"         json:"payPrice"`        // 传过来的当时option价                        
    OptionPrice     uint   `orm:"option_price"      json:"optionPrice"`     // 下单时option京东协议价                      
    OptionName      string `orm:"option_name"       json:"optionName"`      // 规格名称                                    
    AfterSaleStatus uint   `orm:"after_sale_status" json:"afterSaleStatus"` // after_sale.status[最后一次]                 
    GoodsThirdSn2   string `orm:"goods_third_sn2"   json:"goodsThirdSn2"`   // 三方子订单号(扩充)                          
    IsComplete      uint   `orm:"is_complete"       json:"isComplete"`      // 是否完成【1:是 2:否】                       
    IsApply         uint   `orm:"is_apply"          json:"isApply"`         // 申请售后【1:是 2:否】                       
    RefundNum       uint   `orm:"refund_num"        json:"refundNum"`       // 售后数量                                    
    IsSend          uint   `orm:"is_send"           json:"isSend"`          // 是否发货【1:是 2:否】                       
    IsRefund        uint   `orm:"is_refund"         json:"isRefund"`        // 是否退款【1:是 2:否】                       
    IsOvertime      uint   `orm:"is_overtime"       json:"isOvertime"`      // 是否超时【1:是 2:否】                       
}


// Orders is the golang structure for table orders.
type Orders struct {
    Id          uint   `orm:"id,primary"   json:"id"`          //                                         
    Sn          string `orm:"sn"           json:"sn"`          // 订单号（父）                            
    SellerId    uint   `orm:"seller_id"    json:"sellerId"`    // 商户id                                  
    AppId       uint   `orm:"app_id"       json:"appId"`       // 应用id                                  
    ChannelId   uint   `orm:"channel_id"   json:"channelId"`   //                                         
    ThirdSn     string `orm:"third_sn"     json:"thirdSn"`     // 三方订单号                              
    PayStatus   int    `orm:"pay_status"   json:"payStatus"`   // 0:未扣款1:扣款成功-1:扣款失败           
    LogisticFee uint   `orm:"logistic_fee" json:"logisticFee"` // 物流费用【分】                          
    GoodsFee    uint   `orm:"goods_fee"    json:"goodsFee"`    // 商品费用【分】                          
    Consignee   string `orm:"consignee"    json:"consignee"`   // 收件人姓名                              
    Phone       string `orm:"phone"        json:"phone"`       // 收件人联系方式                          
    Province    string `orm:"province"     json:"province"`    // 省                                      
    City        string `orm:"city"         json:"city"`        // 市                                      
    Area        string `orm:"area"         json:"area"`        //                                         
    Street      string `orm:"street"       json:"street"`      //                                         
    Address     string `orm:"address"      json:"address"`     //                                         
    Status      int    `orm:"status"       json:"status"`      // 0未处理1:下单成功-1:下单失败-2超额订单  
    Remark      string `orm:"remark"       json:"remark"`      // 备注                                    
    CheckStatus int    `orm:"check_status" json:"checkStatus"` // 0:未检测1:检测成功-1:检测失败           
    CreatedTime uint   `orm:"created_time" json:"createdTime"` // 创建时间                                
    Origin      uint   `orm:"origin"       json:"origin"`      // 1:SCM 2:微盟                            
}


// User is the golang structure for table user.
type User struct {
    Id   uint   `orm:"id,primary" json:"id"`   //   
    Name string `orm:"name"       json:"name"` //   
}


// UserDetail is the golang structure for table user_detail.
type UserDetail struct {
    Uid     uint   `orm:"uid,primary" json:"uid"`     //   
    Address string `orm:"address"     json:"address"` //   
}


// UserScores is the golang structure for table user_scores.
type UserScores struct {
    Id    uint `orm:"id,primary" json:"id"`    //   
    Uid   uint `orm:"uid"        json:"uid"`   //   
    Score uint `orm:"score"      json:"score"` //   
}