// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gof/app/dao/internal"
)

// lssueOrderDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type lssueOrderDao struct {
	*internal.LssueOrderDao
}

var (
	// LssueOrder is globally public accessible object for table lssue_order operations.
	LssueOrder = lssueOrderDao{
		internal.NewLssueOrderDao(),
	}
)

// Fill with you ideas below.