// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gof/app/dao/internal"
)

// orderGoodsDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type orderGoodsDao struct {
	*internal.OrderGoodsDao
}

var (
	// OrderGoods is globally public accessible object for table order_goods operations.
	OrderGoods = orderGoodsDao{
		internal.NewOrderGoodsDao(),
	}
)

// Fill with you ideas below.