// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gof/app/dao/internal"
)

// ordersDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type ordersDao struct {
	*internal.OrdersDao
}

var (
	// Orders is globally public accessible object for table orders operations.
	Orders = ordersDao{
		internal.NewOrdersDao(),
	}
)

// Fill with you ideas below.