// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"gof/app/dao/internal"
)

// userDetailDao is the manager for logic model data accessing and custom defined data operations functions management. 
// You can define custom methods on it to extend its functionality as you wish.
type userDetailDao struct {
	*internal.UserDetailDao
}

var (
	// UserDetail is globally public accessible object for table user_detail operations.
	UserDetail = userDetailDao{
		internal.NewUserDetailDao(),
	}
)

// Fill with you ideas below.