// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// OrderGoodsDao is the manager for logic model data accessing and custom defined data operations functions management.
type OrderGoodsDao struct {
	Table   string          // Table is the underlying table name of the DAO.
	Group   string          // Group is the database configuration group name of current DAO.
	Columns OrderGoodsColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// OrderGoodsColumns defines and stores column names for table order_goods.
type OrderGoodsColumns struct {
	Id               string // ID                                          
    OrderId          string // 订单ID                                      
    GoodsOrderSn     string // 子订单sn                                    
    GoodsId          string // 商品id                                      
    GoodsImage       string // 商品图片                                    
    OptionId         string // 规格id                                      
    Title            string // 商品名称                                    
    Total            string // 商品总数                                    
    Price            string // 商品价格分                                  
    RefundTime       string // 退款时间                                    
    CreatedTime      string // 创建时间                                    
    GoodsThirdSn     string // 三方子订单号                                
    RealSource       string // 真实来源                                    
    Source           string // 商品来源【1:云仓2:京东6:阿里7:天猫8:苏宁】  
    PayStatus        string // 付款状态【0:未付款,1:已付款】               
    DeliverName      string // 物流公司                                    
    DeliverNo        string // 物流单号                                    
    DeliverTime      string // 发货时间                                    
    PayPrice         string // 传过来的当时option价                        
    OptionPrice      string // 下单时option京东协议价                      
    OptionName       string // 规格名称                                    
    AfterSaleStatus  string // after_sale.status[最后一次]                 
    GoodsThirdSn2    string // 三方子订单号(扩充)                          
    IsComplete       string // 是否完成【1:是 2:否】                       
    IsApply          string // 申请售后【1:是 2:否】                       
    RefundNum        string // 售后数量                                    
    IsSend           string // 是否发货【1:是 2:否】                       
    IsRefund         string // 是否退款【1:是 2:否】                       
    IsOvertime       string // 是否超时【1:是 2:否】
}

//  orderGoodsColumns holds the columns for table order_goods.
var orderGoodsColumns = OrderGoodsColumns{
	Id:              "id",                 
            OrderId:         "order_id",           
            GoodsOrderSn:    "goods_order_sn",     
            GoodsId:         "goods_id",           
            GoodsImage:      "goods_image",        
            OptionId:        "option_id",          
            Title:           "title",              
            Total:           "total",              
            Price:           "price",              
            RefundTime:      "refund_time",        
            CreatedTime:     "created_time",       
            GoodsThirdSn:    "goods_third_sn",     
            RealSource:      "real_source",        
            Source:          "source",             
            PayStatus:       "pay_status",         
            DeliverName:     "deliver_name",       
            DeliverNo:       "deliver_no",         
            DeliverTime:     "deliver_time",       
            PayPrice:        "pay_price",          
            OptionPrice:     "option_price",       
            OptionName:      "option_name",        
            AfterSaleStatus: "after_sale_status",  
            GoodsThirdSn2:   "goods_third_sn2",    
            IsComplete:      "is_complete",        
            IsApply:         "is_apply",           
            RefundNum:       "refund_num",         
            IsSend:          "is_send",            
            IsRefund:        "is_refund",          
            IsOvertime:      "is_overtime",
}

// NewOrderGoodsDao creates and returns a new DAO object for table data access.
func NewOrderGoodsDao() *OrderGoodsDao {
	return &OrderGoodsDao{
		Group:   "default",
		Table:   "order_goods",
		Columns: orderGoodsColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *OrderGoodsDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *OrderGoodsDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *OrderGoodsDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}