// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
)

// UserDetailDao is the manager for logic model data accessing and custom defined data operations functions management.
type UserDetailDao struct {
	Table   string          // Table is the underlying table name of the DAO.
	Group   string          // Group is the database configuration group name of current DAO.
	Columns UserDetailColumns // Columns is the short type for Columns, which contains all the column names of Table for convenient usage.
}

// UserDetailColumns defines and stores column names for table user_detail.
type UserDetailColumns struct {
	Uid      string //   
    Address  string //
}

//  userDetailColumns holds the columns for table user_detail.
var userDetailColumns = UserDetailColumns{
	Uid:     "uid",      
            Address: "address",
}

// NewUserDetailDao creates and returns a new DAO object for table data access.
func NewUserDetailDao() *UserDetailDao {
	return &UserDetailDao{
		Group:   "default",
		Table:   "user_detail",
		Columns: userDetailColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *UserDetailDao) DB() gdb.DB {
	return g.DB(dao.Group)
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *UserDetailDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.Table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *UserDetailDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}